### ISSUE TITLE
TODO images API

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#151]
* [x] Make sure all attributes are available in the model See https://github.com/c2corg/v6_api/pull/154
* [x] Make sure activities attribute can contain several values (see https://github.com/c2corg/v6_api/issues/45)
* [x] Create v5>v6 migration script See https://github.com/c2corg/v6_api/pull/154
* [x] Support file upload 
* [x] Image storage See https://github.com/c2corg/v6_api/issues/167
* [ ] Process uploaded files (create thumbnails, etc.)  See #168
* [x] Index images with ES

**Comment by gberaudo** [comment]
I checked the code of v5 at https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/images/actions/actions.class.php#L580-L642

It appears currently accepted formats are gif, jpeg, png, svg (get rasterized by the backend). Is it the same scope for v6?

c2corg=# select count(*), substring(filename from position('.' in filename)) from app_images_archives group by substring(filename from position('.' in filename));
 count  | substring 
--------+-----------
    319 | .gif
 471878 | .jpg
   3035 | .png

**Comment by asaunier** [comment]
> It appears currently accepted formats are gif, jpeg, png, svg (get rasterized by the backend). Is it the same scope for v6?

Yes.
Please note that in v6, since the target browsers all support SVG natively we probably no longer need to rasterize the SVG => could be served as is, I think.

**Comment by tsauerwein** [comment]
@arnaud-morvan Is this issue complete?

**Comment by asaunier** [comment]
This issue seems to be complete. Please reopen if not.
