### ISSUE TITLE
TODO accounts

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#218]
* [x] Make sure the user cannot ask for a new password until the account is validated.
* [x] Get the guidebook name and forum name when registering.
* [x] CAPTCHA
* [x] Clean non validated users

**Comment by asaunier** [comment]
For the records here are the comments from #195 

@gberaudo 
> When a user is registered but the email is not validated in the delay, the user must be deleted.
See also https://github.com/c2corg/v6_api/pull/190#discussion_r57027022.

@tsauerwein 
> Or rather:
>>Maybe it would make sense to delay the creation of the user-profile until the account is confirmed. Otherwise un-confimed users might show up in the search and listings.

@asaunier
> +1 with @tsauerwein proposal: no use creating the profile until the account is confirmed.
