### ISSUE TITLE
Activity feed

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#403]
The activity feed contains changes for the following actions:

1. A user creates a new document (all document types except outing or image)
2. A user creates a new outing.
3. A user is associated to an existing outing.
4. A set of images is uploaded and associated to a document.

**TODO**

* [x] Set up database model
 * [x] Set up triggers for PK-FK-relation check for `users_ids` and `area_ids` in `DocumentChange`
 * [x] Review indices on feed table
 * [x] Add option `followed_users_updates_only` (maybe with a shorter name `followed_only`?) see https://github.com/c2corg/v6_api/issues/403#issuecomment-250703021
* [x] Import existing data
* [x] Test if performance is ok with existing data
* [x] Update web-services so that the feed tables are updated for the above actions (see https://github.com/c2corg/v6_api/pull/431)
  * [x] When a new document is created (no user or image).
  * [x] When a new user is associated to an outing.
  * [x] When a group of images is uploaded.
* [x] Implement web-services
  * [x] to get feed for homepage (public)
  * [x] to get feed for homepage (authenticated)
  * [x] to get feed for user-profile
  * [x] to follow user (see #401)
  * [x] to get info if following a user (see #401)
  * [x] to get/update filter preferences (see #402)
* [x] Add parameter to get personal homepage feed without filters (see https://github.com/c2corg/v6_api/pull/409#discussion_r82415016)
* [x] Deal with redirected documents

**Comment by asaunier** [comment]
One more thing: would it be possible to take the "quality" attribute into account when filling the feed?

One of the goals of this "quality" field was to strip empty outings (poor quality) out of the homepage for instance. It means that outings (or any documents) created with quality < draft (?) should not be added to the table ``FeedDocumentChanges`` (unless its ``quality`` is upgraded?). What do you think?

**Comment by asaunier** [comment]
The default quality when creating an outing is "draft".
I guess many people will forget to upgrade the quality and their outings won't be shown in the home feed...

**Comment by tsauerwein** [comment]
> One of the goals of this "quality" field was to strip empty outings (poor quality) out of the homepage for instance. It means that outings (or any documents) created with quality < draft (?) should not be added to the table FeedDocumentChanges (unless its quality is upgraded?). What do you think?

This is more a UX problem, encouraging users only to create outings that have content.

**Comment by asaunier** [comment]
> This is more a UX problem, encouraging users only to create outings that have content.

That's not that simple. You have many people that use c2c as a notebook for the outings they have done, a kind of checklist, with no info at all. Just have a look at the current outings in http://www.camptocamp.org/outings => almost all empty! That's not always the case of course but image that all those outings were filling the homepage...
That's not a UX issue.

**Comment by asaunier** [comment]
One more thing :P 

Would it be possible to get only feed items related to people you follow (ie. to apply filters that remove all  items and than to add "followed" items)?

**Comment by tsauerwein** [comment]
You mean an option "Only get updates from followed users"?

**Comment by asaunier** [comment]
Yes, sort of.
A pure social media logic.

**Comment by tsauerwein** [comment]
Yes, that would make sense.
