### ISSUE TITLE
Todo for area searching

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#419]
- [x] support the `atyp` (area_type) filter in the search mapping https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/area_mapping.py
- [x] ~~add areas to the simple search results~~ (already OK)
- [ ] return (simplified?) geometry in list requests? (see https://github.com/c2corg/v6_common/commit/3ff44c360bcbe87d366ecff1f4d11e47017de3ea)

**Comment by tsauerwein** [comment]
This issue is now a duplicate of https://github.com/c2corg/v6_api/issues/489, closing.
