### ISSUE TITLE
Outing's information: add rating attribute

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#685]
Add a "rating" attribute to an outing. Rating = full rating of the activity (same as route)
This attribute shall be filled in only in the followings configuration: there is only one activity and only one route associated to the outing. In all other configuration, this attribute shall be left empty.

see also: https://github.com/c2corg/v6_ui/issues/1550 and https://github.com/c2corg/v6_ui/issues/1800

**Comment by desnoes** [comment]
@asaunier:  @brunobesson has some ideas about the result that should be prodided by the API to the UI. Could you detail your views Bruno ?

**Comment by asaunier** [comment]
Issue https://github.com/c2corg/v6_api/issues/684 (nb of associated images in a list of documents) is probably pretty close to the current issue.

**Comment by asaunier** [comment]
How it was done in v5:
1. the list of outings is retrieved normally (with no route ratings) [1 DB request] https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/outings/actions/actions.class.php#L618
1. associated routes ratings are added using an additional tool (*) https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/outings/actions/actions.class.php#L648

(*) Ratings are retrieved by
1. getting the list of ids of the associated routes [1 DB request] https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/Outing.class.php#L865
1. route ratings for the list of route ids retrieved above are then requested [1 DB request]: https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/Outing.class.php#L901
1. ratings are summarized/merged (depending on the activity, etc.) for each outing and injected to the outings results https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/Outing.class.php#L903-L948

**Comment by desnoes** [comment]
Here is the list of ratings that shoukd be added to attributes of an outing:

- skitouring: ski rating ('toponeige'), global ski rating ('labande')
- snowshoeing: snowshoe rating
- kiking: hiking rating
- snow, ice and mixed: global rating, difficulties height difference and engagement rating
- mountain climbing: global rating, difficulties height difference and engagement rating
- rock climbing: global rating, quality of in-place protections, rock climbing free rating
- ice climbing: Ice climbing rating
- via ferrata: via ferrata rating
- mountain biking: Mountain bike rating down, Mountain bike rating up


It should be possible to filter outings according to the ratings specified above for each activity.

**Comment by asaunier** [comment]
Thanks @desnoes 
We really really need precise instructions for this task. For me it is still way too blur.

Could you provide the real attribute names as used in the database? See https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L28

Are you really sure for "difficulties height difference"? That's not a rating and it's actually a part of the engagement_rating. In addition it could be confused with the actualy height difference of the outing. I recommend to drop this attribute.

Are the rating attributes the ones from the associated routes? Or should they be stored and edited in the outing documents themselves?

If using the associated routes ratings:
* What about outings with several associated routes?
* I guess only ratings for the outings activities are relevant, right?
* What if the outing's activity does not exist for the associated route? (eg. a skitouring outing on an hiking route)

Are the outing's ratings set once for all or should they be updated when the associated routes are changed?

**Comment by desnoes** [comment]
@asaunier: i have completed the spec based on your questions.
Concerning "difficulties height difference", this criterion was used in the "Grande course" portail. This is the reason why it is specified.

**Comment by asaunier** [comment]
@desnoes 

> i have completed the spec based on your questions.

Sorry, I don't see where? Please give detailed instructions in this issue.

**Comment by desnoes** [comment]
@asaunier: it seems i have forgottent to save my modifications grrrrr!!!

**Comment by desnoes** [comment]
@asaunier : here is the list of ratings that should be added to attributes of an outing:

- skitouring: ski_rating  and labande_ski_rating 
- snowshoeing: snowshoe_rating
- hiking: hiking_rating
- snow, ice and mixed: global_rating, height_diff_difficulties and engagement_rating
- mountain climbing: global_rating, height_diff_difficulties and engagement_rating
- rock climbing: global_rating, equipment_rating , rock_free_rating
- ice climbing: ice_rating
- via ferrata: via_ferrata_rating 
- mountain biking: mtb_up_rating and mtb_down_rating

Here are additional specifications:

- The rating attributes are the ones from the associated routes.
- Only ratings for the outings activities should be considered.
- If the outing's activity does not exist for the associated route, rating attributes are not stored
- In case of multiple associated routes with or without the same activity, the rating attributes of each route shall be stored together with the activity type.

It should be possible to filter outings according to the ratings specified above for each activity.

**Comment by asaunier** [comment]
@desnoes Thanks for the info!

> In case of multiple associated routes with or without the same activity, the rating attributes of each route shall be stored together with the activity type.

This is not clear and you don't answer my question.

Say a rock climbing outing is associated to:
* route 1 rated TD P2 6a
* route 2 rated D P1 5c
what should be the ratings of the outing?

Or skitouring outing with:
* route 1 rated AD
* route 2 rated 5.1
what should be the ratings of the outing?

**Comment by desnoes** [comment]
My idea is to have a table which number of entries is the number of routes (minus the routes whose activity does not match with the outing's activity).
Fo each entry, the table should contain the route's activity matching with the outing's activity and the rating attributes defined above for the corresponding activity.
With your example, this would give:

- rock climbing:{ {rock climbing, TD, P2, 5c},{rock climbing, D, P1, 5c}}
- skitouring: {{skitouring, ' ', AD},{skitouring, 5.1, ' '}}

This solution also works in case of multiple activities associated to an outing.

**Comment by asaunier** [comment]
I still don't understand: do you mean that listings of outings should provide the ratings of all associated routes matching the outings' activities?

**Comment by desnoes** [comment]
> do you mean that listings of outings should provide the ratings of all associated routes matching the outings' activities?

Yes. It is required for multi-activities, so maybe it is simpler to keep this same functioning even when there is only one activity but sereral routes.

**Comment by fjacon** [comment]
There are 2 **Use Cases**.
- I want to see ratings in the outing cards
- I want to filter outings by rating

**Comment by desnoes** [comment]
Last version of specifications:

- The list of rating's fields supported for each activity is defined in [the comment abobe](https://github.com/c2corg/v6_api/issues/685#issuecomment-333570449).
- The fields attribute are populated manually in the outing's edition form. The fields are displayed depending on the activities selected by the user. There is one rating attribute for each activity.
- Former outings in the DB need to be updated to set their rating's attributes. A script should do the following actions:
    - for each outing, create a rating's attribute for each outing's activity (same as the first 2 bullet points)
    - When many routes with the same activity are associated to the outing, the outing's rating fields are set to the maximum value. For instance, for hiking, if 2 routes are T1and T2, the field is set to T2. For skiing, if the 2 routes are '4.3 F' and '2.3 PD+', the outing's fields are '4.3' and 'PD+' (stupid example for illustration).

**Comment by fjacon** [comment]
Thansks @desnoes !
Is this definitive ? validated ?

**Comment by desnoes** [comment]
The first 3 bullets are validated and definitive. Concerning the script, if not modification accurs until tomorrow (noon), please consider the spec as validated and definitive.

**Comment by asaunier** [comment]
@desnoes 

> There is one rating attribute for each activity.

If you want to display and filter on several ratings for a given activity (eg. ski_rating and labande_ski_rating for skitouring), we need to have dedicated attributes for each rating. According to https://github.com/c2corg/v6_api/issues/685#issuecomment-333570449 it means 2 attributes for skitouring, 2 for MTB, 3 for snow/ice/mixed, 3 for rock_climbing, 3 for mountain_climbing, 1 for the other activities.

**Comment by desnoes** [comment]
@asaunier : you are wright. Sorry, my wording is not appropriate.

**Comment by asaunier** [comment]
TODO:

## Part 1: new attributes

- [ ] add new rating attributes to the outing model
- [ ] create an alembic script to add the new attributes in the outings table in the DB
- [ ] add new rating attributes to the outing lists and details config in https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py

It seems no change is needed in the outing POST/PUT views since it relies on the v6_common config above.

## Part 2: feeling the attributes for the existing outings

- [ ] add update queries to the alembic script of part 1 in order to set the ratings of existing outings

See examples for instance here:
* https://github.com/c2corg/v6_api/blob/master/alembic_migration/versions/8c230a4a0284_add_langs_feed_filter.py
* https://github.com/c2corg/v6_api/blob/master/alembic_migration/versions/d4d360ef69bc_update_public_transportation_types.py

## Part 3: filtering outings on rating attributes

Perhaps something to do in a separated PR!?

- [ ] add rating attributes to outing search mapping at https://github.com/c2corg/v6_api/blob/master/alembic_migration/versions/d4d360ef69bc_update_public_transportation_types.py

**Comment by asaunier** [comment]
@desnoes @stef74 

> skitouring: ski_rating and labande_ski_rating

This means for instance "4.2 S5". Is it correct?
Or do we want ``labande_global_rating`` (F, PD, AD, etc.) instead of ``labande_ski_rating`` (S1, S2, S3, etc.)?

**Comment by desnoes** [comment]
> Or do we want labande_global_rating (F, PD, AD, etc.) instead of labande_ski_rating (S1, S2, S3, etc.)?

This is an error from my side. It is labande_global_rating. Thanks for you vigilance @asaunier !

**Comment by asaunier** [comment]
Thanks @desnoes I have updated your list at https://github.com/c2corg/v6_api/issues/685#issuecomment-333570449

**Comment by asaunier** [comment]
> filling the attributes up for the existing outings

An SQL query to get the max ratings of associated routes:
```
select o.document_id as outing_id, o.activities, max(ski_rating) as ski_rating, max(labande_global_rating) as labande_global_rating, max(snowshoe_rating) as snowshoe_rating, max(hiking_rating) as hiking_rating, max(global_rating) as global_rating, max(height_diff_difficulties) as height_diff_difficulties, max(engagement_rating) as engagement_rating, max(equipment_rating) as equipment_rating, max(rock_free_rating) as rock_free_rating, max(ice_rating) as ice_rating, max(via_ferrata_rating) as via_ferrata_rating, max(mtb_up_rating) as mtb_up_rating, max(mtb_down_rating) as mtb_down_rating from guidebook.routes r, guidebook.associations a, guidebook.outings o where r.document_id = a.parent_document_id and a.parent_document_type = 'r' and a.child_document_type = 'o' and a.child_document_id = o.document_id group by o.document_id, o.activities order by o.document_id desc limit 10;
``` 
TODO:

- [ ] filter ratings depending on the outing activities (we probably need a plpgsql function taking ratings and activities as argument)
- [ ] update the new outing attributes using those data

**Comment by julsbreakdown** [comment]
>   UPDATE guidebook.outings
>     SET ski_rating = (
>         SELECT CASE
>             WHEN 'skitouring' = ANY(activities)
>                 THEN subquery.ski_rating
>             ELSE NULL
>             END
>             ),
> 
>         labande_global_rating = (
>         SELECT CASE
>             WHEN 'skitouring' = ANY(activities)
>                 THEN subquery.labande_global_rating
>             ELSE NULL
>             END
>             ),
> 
>         global_rating = (
>         SELECT CASE
>             WHEN ('snow_ice_mixed' = ANY(activities) AND
>                   'mountain_climbing' = ANY(activities) AND
>                   'rock_climbing' = ANY(activities))
>                 THEN subquery.global_rating
>             ELSE NULL
>             END
>             ),
> 
>         snowshoe_rating = (
>         SELECT CASE
>             WHEN 'snowshoeing' = ANY(activities)
>                 THEN subquery.snowshoe_rating
>             ELSE NULL
>             END
>             ),
> 
>         hiking_rating = (
>         SELECT CASE
>             WHEN 'hiking' = ANY(activities)
>                 THEN subquery.hiking_rating
>             ELSE NULL
>             END
>             ),
> 
>         height_diff_difficulties = (
>         SELECT CASE
>             WHEN ('snow_ice_mixed' = ANY(activities) AND
>                   'mountain_climbing' = ANY(activities))
>                 THEN subquery.height_diff_difficulties
>             ELSE NULL
>             END
>             ),
> 
>         engagement_rating = (
>         SELECT CASE
>              WHEN ('snow_ice_mixed' = ANY(activities) AND
>                   'mountain_climbing' = ANY(activities))
>                 THEN subquery.engagement_rating
>             ELSE NULL
>             END
>             ),
> 
>         equipment_rating = (
>         SELECT CASE
>             WHEN 'rock_climbing' = ANY(activities)
>                 THEN subquery.equipment_rating
>             ELSE NULL
>             END
>             ),
> 
>         rock_free_rating = (
>         SELECT CASE
>             WHEN 'rock_climbing' = ANY(activities)
>                 THEN subquery.rock_free_rating
>             ELSE NULL
>             END
>             ),
> 
>         ice_rating = (
>         SELECT CASE
>             WHEN 'ice_climbing' = ANY(activities)
>                 THEN subquery.ice_rating
>             ELSE NULL
>             END
>             ),
> 
>         via_ferrata_rating = (
>         SELECT CASE
>             WHEN 'via_ferrata' = ANY(activities)
>                 THEN subquery.via_ferrata_rating
>             ELSE NULL
>             END
>             ),
> 
>         mtb_up_rating = (
>         SELECT CASE
>             WHEN 'moutain_biking' = ANY(activities)
>                 THEN subquery.mtb_up_rating
>             ELSE NULL
>             END
>             ),
> 
>         mtb_down_rating = (
>         SELECT CASE
>             WHEN 'mountain_biking' = ANY(activities)
>                 THEN subquery.mtb_down_rating
>             ELSE NULL
>             END
>             )
>         FROM
>             (SELECT
>                 max(r.ski_rating) AS ski_rating,
>                 max(r.labande_global_rating) AS labande_global_rating,
>                 max(r.snowshoe_rating) AS snowshoe_rating,
>                 max(r.hiking_rating) AS hiking_rating,
>                 max(r.global_rating) AS global_rating,
>                 max(r.height_diff_difficulties) AS height_diff_difficulties,
>                 max(r.engagement_rating) AS engagement_rating,
>                 max(r.equipment_rating) AS equipment_rating,
>                 max(r.rock_free_rating) AS rock_free_rating,
>                 max(r.ice_rating) AS ice_rating,
>                 max(r.via_ferrata_rating) AS via_ferrata_rating,
>                 max(r.mtb_up_rating) AS mtb_up_rating,
>                 max(r.mtb_down_rating) AS mtb_down_rating
>             FROM
>                 guidebook.routes r,
>                 guidebook.associations a,
>                 guidebook.outings o
>             WHERE r.document_id = a.parent_document_id AND
>                   a.parent_document_type = 'r' AND
>                   a.child_document_type = 'o' AND
>                   a.child_document_id = o.document_id
>             GROUP BY o.document_id, o.activities)
>             AS subquery

**Comment by julsbreakdown** [comment]
All is done in one query, what do you think

**Comment by asaunier** [comment]
> All is done in one query, what do you think.

Nice :) 

> Saying that using UPDATE is very costly.

How long does it takes? It's not a big deal if the query is a bit long since it will be run only once.

> No index on outings :/

What indexes are missing?

**Comment by julsbreakdown** [comment]
Well I launched the query yesterday and it hasn't finished yet..
On my local database there are no indexes on the outing table.

**Comment by tsauerwein** [comment]
> Well I launched the query yesterday and it hasn't finished yet..

        FROM
            guidebook.routes r,
            guidebook.associations a,
            guidebook.outings o

You are doing a cross-product of the three tables, you might want to use a proper `JOIN`.

**Comment by julsbreakdown** [comment]
Thanks !!
It now runs in under 1s

**Comment by asaunier** [comment]
@julsbreakdown About part 3 of the TODO list at https://github.com/c2corg/v6_api/issues/685#issuecomment-336397857

> add rating attributes to outing search mapping

you have done it in your PR https://github.com/c2corg/v6_api/pull/696 and the task can be checked, right?
