### ISSUE TITLE
Auth TODO

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#70]
- [x] add user table and methods;
- [x] add stubbed user creation methods;
- [x] add constraint on user on history_metadata (set user when creating a document version)
- [x] set user in migration script
- [x] store and retrieve and delete active tokens from database;
- [x] add token refresh method;
- [x] add or modify unit tests to check methods permissions;
- [x] ~~read and write cookies? (see https://github.com/c2corg/v6_api/wiki/Authentication-Concept)~~
- [x] check password migration from v5, notably unicode passwords
- [x] add index to the token table on the value
- [x] discourse integration
- [x] clean expired tokens from database (see https://github.com/c2corg/v6_api/commit/bbdef2a1c687dd668a1318836cd4b3cf87733529)

**Comment by asaunier** [comment]
@gberaudo Could you please update the above list status?

**Comment by asaunier** [comment]
Can the "discourse integration" item be checked?

**Comment by gberaudo** [comment]
Done

**Comment by asaunier** [comment]
What remains to do with 
> ￼ clean expired tokens from database (see bbdef2a)

?

**Comment by gberaudo** [comment]
Yes

**Comment by asaunier** [comment]
I mean, what should be done with this task since there's a commit that seems to do the job? :P

**Comment by gberaudo** [comment]
This commit was actually reverted later following @tsauerwein request.
